### ISSUE TITLE
Add Google Cloud Functions support

### ISSUE THREAD

**Issue by alexandreyy** [globocom/gcloud-utils#12]
Create package to create, deploy and execute Google Cloud Functions.

Reference
https://cloud.google.com/functions/docs/

**Comment by hericlesme** [comment]
Hi! I'd like to work on this issue. :nerd_face:

**Comment by hericlesme** [comment]
@alexandreyy I'm a little confused about the difference between creating and deploying functions. Can you explain me better?

**Comment by alexandreyy** [comment]
It`s the same process. :)
Take a look at this reference for Python:
https://cloud.google.com/functions/docs/quickstart
Include a validation of the function, if possible:
check if the function exists in the package.

**Comment by hericlesme** [comment]
Great, that's what I thought.
Okay, I'll check this. :)

**Comment by hericlesme** [comment]
@alexandreyy Just one more thing. To indicate which function will be created, should I indicate the path of the function? Or is there another way you prefer?

**Comment by alexandreyy** [comment]
@hericlesme Yes. We can indicate the path as an optional argument . The default should be the current path. And the path should be the directory path of the script main.py.
