### ISSUE TITLE
Replace googleapiclient with dataproc python package

### ISSUE THREAD

**Issue by alexandreyy** [globocom/gcloud-utils#15]
Replace googleapiclient library with dataproc python package in dataproc module.

Reference
https://googleapis.dev/python/dataproc/latest/index.html

**Comment by eulercamposbarros** [comment]
The [Python Client for Google Cloud Dataproc API](https://googleapis.dev/python/dataproc/latest/index.html#deprecated-python-versions) will stop supporting Python 2.7 on the next few months.

Will this library keep supporting python 2.7?

**Comment by alexandreyy** [comment]
Officially no. However, it's important to try to keep the compatibility for python 2.7 if possible.

**Comment by thepabloaguilar** [comment]
`dataproc` package no longer supports Python 2.7, if you want to use it you'll have to drop compatibility with Python 2.7!
Btw, python core developers do not support anything more of version 2.
