### ISSUE TITLE
Fix lint of files

### ISSUE THREAD

**Issue by dmvieira** [globocom/gcloud-utils#16]
There are a lot of lint errors in files.

Run
```
make lint
```
We need to fix these lint issues to CI stay green: https://travis-ci.org/globocom/gcloud-utils

**Comment by rafaeelaudibert** [comment]
Hey! I will try to give a look at this.

**Comment by alexandreyy** [comment]
Resolved by https://github.com/globocom/gcloud-utils/commit/ba8238ae4f2347a425675e61513fc177d918fc65 and https://github.com/globocom/gcloud-utils/commit/db6bad8b53209844d93d8781be81abf29670ba28
