### ISSUE TITLE
Add GCloud logging

### ISSUE THREAD

**Issue by alexandreyy** [globocom/gcloud-utils#18]
Add GCloud logging and adjust our logs to use it.

Reference
https://googleapis.dev/python/logging/latest/index.html

**Comment by isaiastavares** [comment]
I'll take a look at this

**Comment by punitaojha** [comment]
@isaiastavares are you still working upon the task?

**Comment by osmarpetry** [comment]
@isaiastavares still working on it?

**Comment by isaiastavares** [comment]
Guys, sorry for the delay.

I had a personal problem and I won't be able to get this task anymore. If anyone wants to get it, feel free.
